package db

import "context"

// This file is written by hand, not generated by sqlc.
//
// It holds the aggregation behind `crush ccusage`, which reports token
// usage per day and model. That report cannot be built from the columns
// on the sessions table: those record only the most recent turn's
// context size (see updateSessionTokenCounters), so summing them
// measures how large conversations got, not how many tokens were spent.
// The per-turn "usage" part stored on assistant messages is the only
// cumulative record, so this query sums that instead.
//
// Note there is deliberately no parent_session_id filter here: sub-agent
// sessions carry the majority of token spend on a sub-agent-heavy
// workload, and excluding them (as the older stats queries do) badly
// understates real usage.
const getDailyTokenUsage = `
SELECT
    date(m.created_at, 'unixepoch') AS day,
    COALESCE(m.model, '') AS model,
    COALESCE(m.provider, '') AS provider,
    COUNT(*) AS turns,
    CAST(COALESCE(SUM(json_extract(p.value, '$.data.input_tokens')), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(json_extract(p.value, '$.data.output_tokens')), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(json_extract(p.value, '$.data.cache_creation_tokens')), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(json_extract(p.value, '$.data.cache_read_tokens')), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(json_extract(p.value, '$.data.cost')), 0.0) AS REAL) AS recorded_cost
FROM messages m, json_each(m.parts) p
WHERE json_extract(p.value, '$.type') = 'usage'
GROUP BY day, m.model, m.provider
ORDER BY day DESC, input_tokens + output_tokens + cache_creation_tokens + cache_read_tokens DESC
`

// DailyTokenUsageRow is one day's token spend for a single model.
type DailyTokenUsageRow struct {
	Day                 string `json:"day"`
	Model               string `json:"model"`
	Provider            string `json:"provider"`
	Turns               int64  `json:"turns"`
	InputTokens         int64  `json:"input_tokens"`
	OutputTokens        int64  `json:"output_tokens"`
	CacheCreationTokens int64  `json:"cache_creation_tokens"`
	CacheReadTokens     int64  `json:"cache_read_tokens"`
	// RecordedCost is the cost Crush itself billed for these turns. It is
	// 0 for flat-rate subscription providers, which is why the report
	// derives its own cost from token counts and model pricing.
	RecordedCost float64 `json:"recorded_cost"`
}

// GetDailyTokenUsage returns token spend grouped by day and model, newest
// day first.
func (q *Queries) GetDailyTokenUsage(ctx context.Context) ([]DailyTokenUsageRow, error) {
	rows, err := q.query(ctx, nil, getDailyTokenUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyTokenUsageRow{}
	for rows.Next() {
		var i DailyTokenUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.Provider,
			&i.Turns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.RecordedCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
